### PR TITLE
append null to ostringstream will make c_str return part of a string.

### PR DESCRIPTION
**Pull request by xquanluu**

### CODE REVIEW

**Comment by davehorton** [comment]
please show examples of what you were getting before and after this change

**Comment by xquanluu** [comment]
Before:
```
9d86692a-eaaa-4605-b666-b768432b79db 2024-06-27 16:05:33.438548 63.70% [DEBUG] azure_transcribe_glue.cpp:341 hasConfigurationChanged: old configurattion: 1;en-US;1;8000;eastus;redacted-subscription;, new configuration: 1;en-US;1;8000;eastus;redacted-subscription;
```

After:

```
cc76b8e3-41dc-4f95-a233-b432f70dff89 2024-06-27 16:15:50.026916 84.47% [DEBUG] azure_transcribe_glue.cpp:341 hasConfigurationChanged: old configurattion: 1;en-US;1;8000;eastus;redacted-subscription;output_format_detailed;, new configuration: 1;en-US;1;8000;eastus;redacted-subscription;output_format_detailed;vi-VN,en-US;
```

**Comment by vdharashive** [comment]
@xquanluu are we checking for any change in configuration or specific keys ?

**Comment by xquanluu** [comment]
Fixed review comment

**Comment by xquanluu** [comment]
Hi @vdharashive 
We do check for a specific list of keys that freswitch module is using for making connection to azure.

**Comment by vdharashive** [comment]
@xquanluu 

from below keys which are been considered 

AZURE_SPEECH_ALTERNATIVE_LANGUAGE_CODES=^AZURE_USE_OUTPUT_FORMAT_DETAILED=1^AZURE_SUBSCRIPTION_KEY=^AZURE_REGION=eastus^AZURE_SPEECH_HINTS=^AZURE_SERVICE_ENDPOINT_ID=^AZURE_REQUEST_SNR=^AZURE_PROFANITY_OPTION=^AZURE_SERVICE_ENDPOINT=^AZURE_INITIAL_SPEECH_TIMEOUT_MS=^AZURE_SPEECH_SEGMENTATION_SILENCE_TIMEOUT_MS

**Comment by xquanluu** [comment]
Yes those are all keys will make freeswitch kill the old connection if the values are changed

**Comment by xquanluu** [comment]
they confirmed PR is working

**Review by davehorton — APPROVED** [review]

**Pull request merged**
